# SPDX-License-Identifier: AGPL-3.0-only WITH LICENSE-ADDITIONAL
# Copyright (C) 2025 Петунин Лев Михайлович
#Для хранения глобальных конфигураций
#Переменные проекта
URL_CONFIG_MODULES=http://app-config-service:9443
URL_AUTH_USER_MODULES=http://auth-user-app-service:9443
URL_AUDIT_MODULES=http://app-audit-service:9443

#DATABASE CONF
DB_NAME=EOS-DEV
DB_SCHEMA=public
DB_REPLICATION=false
MASTER_HOST=database
MASTER_PORT=5432
SLAVE_HOST=
SLAVE_PORT=
DB_POOL_SIZE=5
DB_MAX_OVERFLOW=10
DB_POOL_TIMEOUT=60
DB_POOL_RECYCLE=3600
DB_POOL_PRE_PING=true
DB_POOL_USE_LIFO=true
DB_MAX_RETRIES=5,
RETRY_DELAY=5


#Переменные приложения
NAME_APP=User-Authorization-Module
#Уровень логирования
LOG_LVL=DEBUG
#Идентификато приложения
MODULE_ID=EOS-UAM
